# Generated by Django 4.1.7 on 2023-05-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_transaction_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='version',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
