# Generated by Django 4.1.7 on 2023-05-11 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_transaction_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.IntegerField(choices=[('GET_TRANSACTIONS', 'Get transactions'), ('GET_USERS_DETAILS', 'Get users_details')], null=True)),
                ('uid', models.CharField(max_length=10, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('version', models.PositiveIntegerField(default=0, null=True)),
            ],
            options={
                'verbose_name': 'event',
            },
        ),
    ]
