# Generated by Django 4.1.7 on 2023-05-11 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
