# Generated by Django 4.1.7 on 2023-05-11 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_date_transaction_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date_trans',
            field=models.DateTimeField(blank=True, help_text='Date of last Transaction', null=True, verbose_name='Last Transaction'),
        ),
    ]
